// Copyright (c) 2026 Jacken Xu (lightant@gmail.com)
// All rights reserved.

import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers/records_provider.dart';
import '../providers/profile_provider.dart';
import '../providers/view_data_provider.dart';
import '../providers/settings_provider.dart';
import '../services/insight_service.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../l10n/generated/app_localizations.dart';
import 'package:gemini_nano_android/gemini_nano_android.dart';
import '../services/gemma_inference_service.dart';
import '../providers/api_key_provider.dart';

final insightServiceProvider = Provider((ref) {
  final apiKey = ref.watch(apiKeyProvider);
  return InsightService(apiKey);
});

// Notifier that handles generation and persistence of insights
final insightProvider = AsyncNotifierProvider<InsightNotifier, String>(
  InsightNotifier.new,
);

class InsightNotifier extends AsyncNotifier<String> {
  static const _cacheKey = 'gemini_insight_report';

  @override
  Future<String> build() async {
    final prefs = await SharedPreferences.getInstance();
    final cached = prefs.getString(_cacheKey);

    if (cached != null && cached.isNotEmpty) {
      return cached;
    }

    return "TAP_TO_GENERATE";
  }

  Future<void> generateInsights() async {
    state = const AsyncLoading();

    try {
      final profile = ref.read(profileProvider);
      final records = ref.read(recordsProvider);

      if (profile == null || records.isEmpty) {
        state = const AsyncData("Please sync your health data first to get insights.");
        return;
      }

      final viewData = ref.read(viewDataProvider);
      final settings = ref.read(settingsProvider);
      final languageCode = settings.locale.languageCode;
      final service = ref.read(insightServiceProvider);

      String finalResult = "";
      final buffer = StringBuffer();

      if (settings.aiSource == AiSource.aiCore) {
        if (defaultTargetPlatform != TargetPlatform.android || kIsWeb) {
          state = const AsyncData("Local AI (Gemini Nano) is only supported on Android.");
          return;
        }

        final nano = GeminiNanoAndroid();
        final isReady = await nano.isAvailable();
        if (!isReady) {
          state = const AsyncData("Local AI (Gemini Nano) is not ready.");
          return;
        }

        final prompt = service.buildPrompt(profile, records, avgHr: viewData.stats.avg, minHr: viewData.stats.min, peakHr: viewData.stats.peak, languageCode: languageCode);
        final responses = await nano.generate(prompt: prompt, maxOutputTokens: 1024);
        finalResult = responses.isNotEmpty ? "_[Generated by On-Device AI (AICore)]_\n\n${responses.first}" : "No insights generated.";
        state = AsyncData(finalResult);
      } else if (settings.aiSource == AiSource.gemmaInApp) {
        state = const AsyncData("_[Initializing In-APP AI (Gemma)]_ ⏳");
        final gemmaService = GemmaInferenceService();
        await gemmaService.initModel();

        state = const AsyncData("_[Gemma: Starting Generation...]_ ⏳");
        final prompt = service.buildPrompt(profile, records, avgHr: viewData.stats.avg, minHr: viewData.stats.min, peakHr: viewData.stats.peak, languageCode: languageCode);
        
        buffer.write("_[Generated by Gemma On-Device AI]_\n\n");
        await for (final chunk in gemmaService.generateResponseStream(prompt)) {
          buffer.write(chunk);
          state = AsyncData(buffer.toString());
        }
        finalResult = buffer.toString();
      } else {
        // Cloud generation with streaming
        state = const AsyncData("_[Generating Insights with Gemini Cloud...]_ ⏳");
        await for (final chunk in service.getHealthInsightsStream(profile, records, avgHr: viewData.stats.avg, minHr: viewData.stats.min, peakHr: viewData.stats.peak, languageCode: languageCode)) {
          buffer.write(chunk);
          state = AsyncData(buffer.toString());
        }
        finalResult = buffer.toString();
      }

      // Persist the final result only when finished
      if (finalResult.isNotEmpty) {
        final prefs = await SharedPreferences.getInstance();
        await prefs.setString(_cacheKey, finalResult);
      }
    } catch (e, st) {
      state = AsyncError(e, st);
    }
  }
}

class InsightView extends ConsumerStatefulWidget {
  const InsightView({super.key});

  @override
  ConsumerState<InsightView> createState() => _InsightViewState();
}

class _InsightViewState extends ConsumerState<InsightView> {
  final ScrollController _scrollController = ScrollController();

  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }

  void _scrollToBottom() {
    if (_scrollController.hasClients) {
      _scrollController.animateTo(
        _scrollController.position.maxScrollExtent,
        duration: const Duration(milliseconds: 200),
        curve: Curves.easeOut,
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final insightsAsync = ref.watch(insightProvider);
    final l10n = AppLocalizations.of(context)!;

    // Trigger auto-scroll on any text update during streaming
    ref.listen(insightProvider, (previous, next) {
      if (next is AsyncData) {
        WidgetsBinding.instance.addPostFrameCallback((_) => _scrollToBottom());
      }
    });

    return Scaffold(
      appBar: AppBar(title: Text(l10n.insights)),
      body: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Row(
                  children: [
                    const Icon(Icons.auto_awesome, color: Colors.amber),
                    const SizedBox(width: 8),
                    Text(
                      l10n.yourReport,
                      style: Theme.of(context).textTheme.titleLarge?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ],
                ),
                IconButton(
                  onPressed: () {
                    ref.read(insightProvider.notifier).generateInsights();
                  },
                  icon: const Icon(Icons.refresh, size: 36),
                  color: Theme.of(context).primaryColor,
                  tooltip: l10n.regenerate,
                ),
              ],
            ),
            const SizedBox(height: 16),
            Expanded(
              child: insightsAsync.when(
                data: (text) {
                  if (text == "SET_KEY_REQUIRED") {
                    return _buildCenteredMessage(
                      context,
                      icon: Icons.key_off,
                      message: "Please set your Gemini API Key in Settings to generate insights.",
                    );
                  }

                  if (text == "TAP_TO_GENERATE") {
                    return _buildCenteredMessage(
                      context,
                      icon: Icons.analytics_outlined,
                      message: "Tap the refresh button to generate your AI health insights.",
                    );
                  }

                  return SingleChildScrollView(
                    controller: _scrollController,
                    physics: const BouncingScrollPhysics(),
                    child: Padding(
                      padding: const EdgeInsets.only(bottom: 24.0),
                      child: MarkdownBody(
                        data: text,
                        styleSheet: MarkdownStyleSheet.fromTheme(
                          Theme.of(context),
                        ).copyWith(
                          p: const TextStyle(
                            fontSize: 16,
                            height: 1.6,
                            letterSpacing: 0.2,
                          ),
                        ),
                        selectable: true,
                      ),
                    ),
                  );
                },
                loading: () => const Center(child: CircularProgressIndicator()),
                error: (e, _) => Center(child: Text('Error: $e')),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildCenteredMessage(
    BuildContext context, {
    required IconData icon,
    required String message,
    Widget? action,
  }) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(icon, size: 48, color: Colors.orange.withValues(alpha: 0.7)),
          const SizedBox(height: 16),
          Text(message, textAlign: TextAlign.center),
          if (action != null) ...[const SizedBox(height: 16), action],
        ],
      ),
    );
  }
}
